// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQhMQbiOKk2lGMBmNoRMBwj_BbbN_jNF4',
    appId: '1:304058488846:web:a290eec93e16343c29c45f',
    messagingSenderId: '304058488846',
    projectId: 'todoapp-8e30f',
    authDomain: 'todoapp-8e30f.firebaseapp.com',
    storageBucket: 'todoapp-8e30f.appspot.com',
    measurementId: 'G-1D83F49YYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGzY8p5Yg4pUZij36F4QaVRASNQc77iD4',
    appId: '1:304058488846:android:7aef12d999cddd1d29c45f',
    messagingSenderId: '304058488846',
    projectId: 'todoapp-8e30f',
    storageBucket: 'todoapp-8e30f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJZ_l9rX2FOpcnCVJ4lP6SD5aTSJ_HDTM',
    appId: '1:304058488846:ios:9d161a13bcb88b0a29c45f',
    messagingSenderId: '304058488846',
    projectId: 'todoapp-8e30f',
    storageBucket: 'todoapp-8e30f.appspot.com',
    iosClientId: '304058488846-85ch5of10hc9tskpdpdlobqtigcdmeo1.apps.googleusercontent.com',
    iosBundleId: 'com.example.hivePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJZ_l9rX2FOpcnCVJ4lP6SD5aTSJ_HDTM',
    appId: '1:304058488846:ios:9d161a13bcb88b0a29c45f',
    messagingSenderId: '304058488846',
    projectId: 'todoapp-8e30f',
    storageBucket: 'todoapp-8e30f.appspot.com',
    iosClientId: '304058488846-85ch5of10hc9tskpdpdlobqtigcdmeo1.apps.googleusercontent.com',
    iosBundleId: 'com.example.hivePractice',
  );
}

